version: 2.1
orbs:
  slack: circleci/slack@4.5.0

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:52:3d:ae:f9:ee:a5:7f:36:6e:af:51:2f:bd:33:25"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/travel-notes/deploy.sh"
      #失敗
      - slack/notify:
          event: fail
          template: basic_fail_1
      #成功
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy
#          filters:
#            branches:
#              only: main
